### ISSUE TITLE
Analisar documento Laysa e Jeferson

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/NIT-Boards#19]
## **Contexto**

- Com a intenção de ajudar novos membros do time iSUS a se ambientarem sozinhos um documento foi elaborado para auxiliar na criação de uma jornada a ser seguida e conteúdos que precisam ser consumidos para o entendimento das rotinas e atividades do time. O próximo passo é filtrar as informações desse documento e uni-las ao desenho da jornada elaborado através do documento: https://docs.google.com/spreadsheets/d/1MjksqB4kLwObazmHUcscf5_RDwe-37Sz354y8oZF2hk/edit#gid=1158327848

## **Escopo**

- [x] Revisão do documento
- [x] Filtrar informações para construção da jornada
- [x] Definir em quais etapas as informações coletadas irão entrar

## Observações
https://docs.google.com/document/d/1Oj0L9WL5fSsoco1arv6_kjcyKcgbD8mnKt9qrNOI81Y/edit#heading=h.2g2e1vxf1egm

**Comment by RaniGub** [comment]
Tarefa encerrada, May confirmou conclusão.
