### ISSUE TITLE
Criar aterfatos da jornada

### ISSUE THREAD

**Issue by MayaraMonte** [FeliciLab/NIT-Boards#22]
## **Contexto**

- Para criar a melhor experiência imersiva para os novos membros dos times vimos a necessidade de criar artefatos para deixar o onboarding mais visual e dentro do tema escolhido. 

## **Escopo**

- [x] Infográfico da jornada
- [x] Emblemas para conclusão de cada etapa
- [x] Pergaminhos (boas vindas e conclusão de etapas)
- [x] Certificado
- [x] Ajustes

**Comment by RaniGub** [comment]
Tarefa encerrada, May confirmou conclusão.
